"""Create talent recommendation run and result snapshots.

Revision ID: 20260730_0033
Revises: 20260729_0032
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260730_0033"
down_revision: str | None = "20260729_0032"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_candidate_profiles_snapshot_identity",
        "candidate_profiles",
        ["id", "document_id", "version_number"],
    )
    op.create_table(
        "talent_recommendation_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("criteria_version_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_username_snapshot", sa.String(length=64), nullable=False),
        sa.Column("created_by_display_name_snapshot", sa.String(length=100), nullable=False),
        sa.Column("idempotency_key", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="queued", nullable=False),
        sa.Column("ai_input_mode", sa.String(length=20), server_default="raw", nullable=False),
        sa.Column("recall_limit", sa.Integer(), server_default="50", nullable=False),
        sa.Column("rescore_limit", sa.Integer(), server_default="20", nullable=False),
        sa.Column("criteria_snapshot", sa.JSON(), nullable=False),
        sa.Column("embedding_model_snapshot", sa.String(length=200), nullable=False),
        sa.Column("ai_model_snapshot", sa.String(length=200), nullable=False),
        sa.Column("prompt_version_snapshot", sa.String(length=100), nullable=False),
        sa.Column("celery_task_id", sa.String(length=100), nullable=True),
        sa.Column("scope_candidate_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("retrieved_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("rescored_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("completed_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("failed_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("excluded_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("criteria_stale", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("criteria_stale_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_code", sa.String(length=80), nullable=True),
        sa.Column("failure_summary", sa.Text(), nullable=True),
        sa.Column("resource_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status IN ('completed', 'partial', 'failed', 'cancelled') "
            "AND completed_at IS NOT NULL) OR "
            "(status NOT IN ('completed', 'partial', 'failed', 'cancelled') "
            "AND completed_at IS NULL)",
            name="ck_talent_recommendation_runs_completed_at",
        ),
        sa.CheckConstraint(
            "ai_input_mode IN ('raw', 'redacted')",
            name="ck_talent_recommendation_runs_ai_input_mode",
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'retrieving', 'rescoring', 'completed', "
            "'partial', 'failed', 'cancelled')",
            name="ck_talent_recommendation_runs_status",
        ),
        sa.CheckConstraint(
            "(criteria_stale = false AND criteria_stale_at IS NULL) OR "
            "(criteria_stale = true AND criteria_stale_at IS NOT NULL)",
            name="ck_talent_recommendation_runs_criteria_stale",
        ),
        sa.CheckConstraint(
            "recall_limit = 50 AND rescore_limit = 20", name="ck_talent_recommendation_runs_limits"
        ),
        sa.CheckConstraint(
            "resource_version >= 1", name="ck_talent_recommendation_runs_resource_version"
        ),
        sa.CheckConstraint(
            "retrieved_count <= recall_limit AND rescored_count <= rescore_limit "
            "AND rescored_count <= retrieved_count "
            "AND completed_count + failed_count <= rescored_count",
            name="ck_talent_recommendation_runs_count_bounds",
        ),
        sa.CheckConstraint(
            "scope_candidate_count >= 0 AND retrieved_count >= 0 "
            "AND rescored_count >= 0 AND completed_count >= 0 "
            "AND failed_count >= 0 AND excluded_count >= 0",
            name="ck_talent_recommendation_runs_counts_nonnegative",
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["criteria_version_id"], ["job_criteria_versions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "job_id", "idempotency_key", name="uq_talent_recommendation_runs_job_idempotency"
        ),
    )
    op.create_index(
        op.f("ix_talent_recommendation_runs_celery_task_id"),
        "talent_recommendation_runs",
        ["celery_task_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_talent_recommendation_runs_created_by_id"),
        "talent_recommendation_runs",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_talent_recommendation_runs_criteria_version_id"),
        "talent_recommendation_runs",
        ["criteria_version_id"],
        unique=False,
    )
    op.create_index(
        "ix_talent_recommendation_runs_job_created",
        "talent_recommendation_runs",
        ["job_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_talent_recommendation_runs_job_id"),
        "talent_recommendation_runs",
        ["job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_talent_recommendation_runs_status"),
        "talent_recommendation_runs",
        ["status"],
        unique=False,
    )
    op.create_table(
        "talent_recommendation_run_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("from_status", sa.String(length=20), nullable=True),
        sa.Column("to_status", sa.String(length=20), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_username_snapshot", sa.String(length=64), nullable=True),
        sa.Column("actor_display_name_snapshot", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('created', 'retrieval_started', 'retrieval_completed', "
            "'rescoring_started', 'completed', 'partial', 'failed', "
            "'cancel_requested', 'cancelled', 'retry_requested', 'stale_marked')",
            name="ck_talent_recommendation_run_events_type",
        ),
        sa.CheckConstraint(
            "from_status IS NULL OR from_status IN "
            "('queued', 'retrieving', 'rescoring', 'completed', "
            "'partial', 'failed', 'cancelled')",
            name="ck_talent_recommendation_run_events_from_status",
        ),
        sa.CheckConstraint(
            "to_status IS NULL OR to_status IN "
            "('queued', 'retrieving', 'rescoring', 'completed', "
            "'partial', 'failed', 'cancelled')",
            name="ck_talent_recommendation_run_events_to_status",
        ),
        sa.CheckConstraint(
            "sequence_number >= 1", name="ck_talent_recommendation_run_events_sequence"
        ),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["run_id"], ["talent_recommendation_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "run_id", "idempotency_key", name="uq_talent_recommendation_run_events_idempotency"
        ),
        sa.UniqueConstraint(
            "run_id", "sequence_number", name="uq_talent_recommendation_run_events_sequence"
        ),
    )
    op.create_index(
        op.f("ix_talent_recommendation_run_events_actor_user_id"),
        "talent_recommendation_run_events",
        ["actor_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_talent_recommendation_run_events_event_type"),
        "talent_recommendation_run_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_talent_recommendation_run_events_run_id"),
        "talent_recommendation_run_events",
        ["run_id"],
        unique=False,
    )
    op.create_table(
        "talent_recommendation_run_groups",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("group_name_snapshot", sa.String(length=100), nullable=False),
        sa.Column("group_version_snapshot", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "group_version_snapshot >= 1", name="ck_talent_recommendation_run_groups_version"
        ),
        sa.CheckConstraint(
            "length(trim(group_name_snapshot)) > 0",
            name="ck_talent_recommendation_run_groups_name_not_blank",
        ),
        sa.ForeignKeyConstraint(["group_id"], ["talent_pool_groups.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["run_id"], ["talent_recommendation_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id", "group_id"),
    )
    op.create_table(
        "talent_recommendation_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("resolved_candidate_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_code_snapshot", sa.String(length=40), nullable=False),
        sa.Column("candidate_name_snapshot", sa.String(length=200), nullable=True),
        sa.Column("candidate_merged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("document_sha256_snapshot", sa.String(length=64), nullable=False),
        sa.Column("document_updated_at_snapshot", sa.DateTime(timezone=True), nullable=False),
        sa.Column("candidate_profile_id", sa.Uuid(), nullable=False),
        sa.Column("profile_version_snapshot", sa.Integer(), nullable=False),
        sa.Column("embedding_model_snapshot", sa.String(length=200), nullable=False),
        sa.Column("embedding_version_snapshot", sa.String(length=100), nullable=False),
        sa.Column("embedding_dimension_snapshot", sa.Integer(), nullable=False),
        sa.Column("vector_rank", sa.Integer(), nullable=False),
        sa.Column("similarity_score", sa.Numeric(precision=9, scale=8), nullable=False),
        sa.Column("matched_group_ids", sa.JSON(), nullable=False),
        sa.Column("matched_chunks", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("ai_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("ai_group", sa.String(length=30), nullable=True),
        sa.Column("ai_dimension_scores", sa.JSON(), nullable=False),
        sa.Column("ai_evidence", sa.JSON(), nullable=False),
        sa.Column("ai_model_snapshot", sa.String(length=200), nullable=True),
        sa.Column("prompt_version_snapshot", sa.String(length=100), nullable=True),
        sa.Column("processing_attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("failure_code", sa.String(length=80), nullable=True),
        sa.Column("failure_message", sa.Text(), nullable=True),
        sa.Column("exclusion_code", sa.String(length=80), nullable=True),
        sa.Column("exclusion_reason", sa.Text(), nullable=True),
        sa.Column("document_stale", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("profile_stale", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("embedding_stale", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("stale_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'completed' AND ai_score IS NOT NULL "
            "AND ai_group IS NOT NULL AND failure_code IS NULL "
            "AND exclusion_code IS NULL AND completed_at IS NOT NULL) OR "
            "(status = 'failed' AND failure_code IS NOT NULL "
            "AND length(trim(failure_code)) > 0 AND exclusion_code IS NULL "
            "AND completed_at IS NOT NULL) OR "
            "(status = 'excluded' AND exclusion_code IS NOT NULL "
            "AND length(trim(exclusion_code)) > 0 AND failure_code IS NULL "
            "AND completed_at IS NOT NULL) OR "
            "(status IN ('retrieved', 'rescoring') AND failure_code IS NULL "
            "AND exclusion_code IS NULL AND completed_at IS NULL)",
            name="ck_talent_recommendation_results_terminal_contract",
        ),
        sa.CheckConstraint(
            "ai_group IS NULL OR ai_group IN ('passed', 'low_match', 'auto_rejected')",
            name="ck_talent_recommendation_results_ai_group",
        ),
        sa.CheckConstraint(
            "status IN ('retrieved', 'rescoring', 'completed', 'failed', 'excluded')",
            name="ck_talent_recommendation_results_status",
        ),
        sa.CheckConstraint(
            "(document_stale = false AND profile_stale = false "
            "AND embedding_stale = false AND stale_at IS NULL) OR "
            "((document_stale = true OR profile_stale = true "
            "OR embedding_stale = true) AND stale_at IS NOT NULL)",
            name="ck_talent_recommendation_results_stale",
        ),
        sa.CheckConstraint(
            "(resolved_candidate_id = candidate_id "
            "AND candidate_merged_at IS NULL) OR "
            "(resolved_candidate_id <> candidate_id "
            "AND candidate_merged_at IS NOT NULL)",
            name="ck_talent_recommendation_results_candidate_resolution",
        ),
        sa.CheckConstraint(
            "ai_score IS NULL OR (ai_score >= 0 AND ai_score <= 100)",
            name="ck_talent_recommendation_results_ai_score",
        ),
        sa.CheckConstraint(
            "length(document_sha256_snapshot) = 64",
            name="ck_talent_recommendation_results_document_sha256",
        ),
        sa.CheckConstraint(
            "length(trim(candidate_code_snapshot)) > 0",
            name="ck_talent_recommendation_results_candidate_code",
        ),
        sa.CheckConstraint(
            "processing_attempt_count >= 0", name="ck_talent_recommendation_results_attempt_count"
        ),
        sa.CheckConstraint(
            "profile_version_snapshot >= 1 AND embedding_dimension_snapshot >= 1",
            name="ck_talent_recommendation_results_versions",
        ),
        sa.CheckConstraint(
            "similarity_score >= -1 AND similarity_score <= 1",
            name="ck_talent_recommendation_results_similarity",
        ),
        sa.CheckConstraint(
            "vector_rank >= 1 AND vector_rank <= 50",
            name="ck_talent_recommendation_results_vector_rank",
        ),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidates.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["candidate_profile_id", "document_id", "profile_version_snapshot"],
            [
                "candidate_profiles.id",
                "candidate_profiles.document_id",
                "candidate_profiles.version_number",
            ],
            name="fk_talent_recommendation_results_profile_snapshot",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["document_id"], ["resume_documents.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["resolved_candidate_id"], ["candidates.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["run_id"], ["talent_recommendation_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "run_id", "candidate_id", name="uq_talent_recommendation_results_run_candidate"
        ),
        sa.UniqueConstraint(
            "run_id", "vector_rank", name="uq_talent_recommendation_results_run_rank"
        ),
    )
    op.create_index(
        op.f("ix_talent_recommendation_results_candidate_id"),
        "talent_recommendation_results",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_talent_recommendation_results_candidate_profile_id"),
        "talent_recommendation_results",
        ["candidate_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_talent_recommendation_results_document_id"),
        "talent_recommendation_results",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_talent_recommendation_results_resolved_candidate_id"),
        "talent_recommendation_results",
        ["resolved_candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_talent_recommendation_results_run_id"),
        "talent_recommendation_results",
        ["run_id"],
        unique=False,
    )
    op.create_index(
        "ix_talent_recommendation_results_run_status",
        "talent_recommendation_results",
        ["run_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_talent_recommendation_results_status"),
        "talent_recommendation_results",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_talent_recommendation_results_status"), table_name="talent_recommendation_results"
    )
    op.drop_index(
        "ix_talent_recommendation_results_run_status", table_name="talent_recommendation_results"
    )
    op.drop_index(
        op.f("ix_talent_recommendation_results_run_id"), table_name="talent_recommendation_results"
    )
    op.drop_index(
        op.f("ix_talent_recommendation_results_resolved_candidate_id"),
        table_name="talent_recommendation_results",
    )
    op.drop_index(
        op.f("ix_talent_recommendation_results_document_id"),
        table_name="talent_recommendation_results",
    )
    op.drop_index(
        op.f("ix_talent_recommendation_results_candidate_profile_id"),
        table_name="talent_recommendation_results",
    )
    op.drop_index(
        op.f("ix_talent_recommendation_results_candidate_id"),
        table_name="talent_recommendation_results",
    )
    op.drop_table("talent_recommendation_results")
    op.drop_table("talent_recommendation_run_groups")
    op.drop_index(
        op.f("ix_talent_recommendation_run_events_run_id"),
        table_name="talent_recommendation_run_events",
    )
    op.drop_index(
        op.f("ix_talent_recommendation_run_events_event_type"),
        table_name="talent_recommendation_run_events",
    )
    op.drop_index(
        op.f("ix_talent_recommendation_run_events_actor_user_id"),
        table_name="talent_recommendation_run_events",
    )
    op.drop_table("talent_recommendation_run_events")
    op.drop_index(
        op.f("ix_talent_recommendation_runs_status"), table_name="talent_recommendation_runs"
    )
    op.drop_index(
        op.f("ix_talent_recommendation_runs_job_id"), table_name="talent_recommendation_runs"
    )
    op.drop_index(
        "ix_talent_recommendation_runs_job_created", table_name="talent_recommendation_runs"
    )
    op.drop_index(
        op.f("ix_talent_recommendation_runs_criteria_version_id"),
        table_name="talent_recommendation_runs",
    )
    op.drop_index(
        op.f("ix_talent_recommendation_runs_created_by_id"), table_name="talent_recommendation_runs"
    )
    op.drop_index(
        op.f("ix_talent_recommendation_runs_celery_task_id"),
        table_name="talent_recommendation_runs",
    )
    op.drop_table("talent_recommendation_runs")
    op.drop_constraint(
        "uq_candidate_profiles_snapshot_identity",
        "candidate_profiles",
        type_="unique",
    )
    # ### end Alembic commands ###
